# Generated by Django 2.1.7 on 2023-02-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_api', '0004_auto_20230201_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_url', models.URLField()),
                ('clicks', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
