# Generated by Django 2.1.7 on 2023-02-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_api', '0005_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicks',
            name='date',
        ),
    ]
