# Generated by Django 2.1.7 on 2023-02-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_api', '0007_clicks_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicks',
            name='clicks',
        ),
        migrations.AlterField(
            model_name='clicks',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
